//Author-Tejasvi Raj Pant

export const FETCH_BOOKS = 'FETCH_BOOKS'
export type FETCH_BOOKS = typeof FETCH_BOOKS

export const FETCH_BOOKS_REQUESTED = 'FETCH_BOOKS_REQUESTED'
export type FETCH_BOOKS_REQUESTED = typeof FETCH_BOOKS_REQUESTED

export const FETCH_BOOKS_SUCCEEDED = 'FETCH_BOOKS_SUCCEEDED'
export type FETCH_BOOKS_SUCCEEDED = typeof FETCH_BOOKS_SUCCEEDED

export const FETCH_BOOKS_FAIL = 'FETCH_BOOKS_FAIL'
export type FETCH_BOOKS_FAIL = typeof FETCH_BOOKS_FAIL



